"""changed name of booking id to id

Revision ID: 2d64e29750db
Revises: 5758b66f3cfd
Create Date: 2021-12-16 12:03:08.662355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d64e29750db'
down_revision = '5758b66f3cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_booking', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('film_booking', 'bookingid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_booking', sa.Column('bookingid', sa.INTEGER(), nullable=False))
    op.drop_column('film_booking', 'id')
    # ### end Alembic commands ###
