"""attempted loan function 2

Revision ID: 4dbf6ba6ba8a
Revises: ae81116869f9
Create Date: 2021-12-15 17:33:05.729237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbf6ba6ba8a'
down_revision = 'ae81116869f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_booking',
    sa.Column('bookingid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('fromdate', sa.DateTime(), nullable=True),
    sa.Column('todate', sa.DateTime(), nullable=True),
    sa.Column('caleventid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['game.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('bookingid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_booking')
    # ### end Alembic commands ###
