"""address table

Revision ID: 507d5a543c1b
Revises: cbe61d76e90b
Create Date: 2021-12-04 20:56:54.704403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507d5a543c1b'
down_revision = 'cbe61d76e90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=50), nullable=True),
    sa.Column('Address2', sa.String(length=50), nullable=True),
    sa.Column('Postal_Code', sa.String(length=10), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('Last_Update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
