"""added show bookings

Revision ID: 5758b66f3cfd
Revises: afb0f1183e53
Create Date: 2021-12-15 22:26:15.299666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5758b66f3cfd'
down_revision = 'afb0f1183e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_booking',
    sa.Column('bookingid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('showid', sa.Integer(), nullable=True),
    sa.Column('fromdate', sa.DateTime(), nullable=True),
    sa.Column('todate', sa.DateTime(), nullable=True),
    sa.Column('req_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['showid'], ['show.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('bookingid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_booking')
    # ### end Alembic commands ###
