"""empty message

Revision ID: 856b8aa5b527
Revises: 1e7559641331
Create Date: 2021-12-06 20:59:47.081115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856b8aa5b527'
down_revision = '1e7559641331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videogames')
    op.add_column('game', sa.Column('loan_status', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'loan_status')
    op.create_table('videogames',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), nullable=True),
    sa.Column('release_year', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
