"""user foriegn fields 

Revision ID: 88061c3bf968
Revises: 507d5a543c1b
Create Date: 2021-12-04 20:57:50.525950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88061c3bf968'
down_revision = '507d5a543c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'address', ['Address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'Address_id')
    # ### end Alembic commands ###
